swagger: "2.0"
info:
  version: 1.0.0
  title: MENTHE
  description: Express Menthe RestAPI server
basePath: /api/v1

tags:
  - name: Users
    description: Everithing about Users
  - name: Content
    description: What the API is made for

consumes:
  - application/json
produces:
  - application/json


definitions:
  UserCredentials:
    type: object
    title: User Login information  
    required:
      - "email"
      - "password"
    properties:
      email:
        type: string
        example: "first.last@domain.com"
      password:
        type: string
        example: "123456789"
  UserInfos:
    type: object
    title: User Information  
    required:
      - "id"
      - "email"
    properties:
      id:
        type: string
        example: "1"
      email:
        type: string
        example: "first.last@domain.com"

paths:
  /signup:
    post:
      tags: 
        - "Users"
      summary:
        "Register a new user"
      parameters:
      - in: "body"
        name: "body"
        description: user credentials 
        required: true
        schema:
          $ref: "#/definitions/UserCredentials"    
      responses:  
        200:
          description: "Successful operation"
        400:
          description: Return errors
  /login:
    post:
      tags:
        - "Users"
      summary:
        "Login with a existing user"
      parameters:
        - in: "body"
          name: "body"
          description: "user credentials"
          required: true
          schema:
            $ref: "#/definitions/UserCredentials"
      responses:
        403:
          description: Authentication error
    options:
      tags:
        - "Users"
      summary:
        "Login with a existing user"
      parameters:
      responses:
        403:
          description: Authentication error
  /logout:
    post:
      tags:
        - "Users"
      summary:
        "Logout the current user"
      description:
        "Cross Site Request Forgery \n You must send back the XSRF-TOKEN cookie in the x-xsrf-token header !\n without the x-xsrf-token header, it will send back 403 - Forbidden"
      parameters:
        - in: "body"
          name: "body"
          description: "user credentials"
          required: false      
      responses:
        200:
          description: User logged out
    options:
      tags:
        - "Users"
      summary:
        "Logout an existing user"
      parameters:
      responses:
        403:
          description: Authentication error
  /user:
    get:
      tags:
        - "Users"
      summary:
        "Get the current user"
      responses:
        403:
          description: Authentication error
  /user/{userId}:
    get:
      tags:
        - "Users"
      summary:
        "Get User by Id"
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          type: string
      responses:
        403:
          description: Authentication error
    delete:
      tags:
        - "Users"
      parameters:
        - name: "userId"
          in: path
          description: ID of user to delete
          required: true
          type: string
      responses:
        403:
          description: Authentication error
  /users:
    get:
      tags:
        - "Users"
      summary:
        "Get All Users"
      responses:
        403:
          description: Authentication error
  
  /content:
    get:
      tags:
        - "Content"
      responses:
        403 : 
          description: Authentication error